CREATE TABLE clients
(
    id                  VARCHAR(50) NOT NULL PRIMARY KEY,
    client_type         VARCHAR(20) NOT NULL, -- INDIVIDUAL / PROFESSIONAL

    -- individual
    first_name          VARCHAR(100),
    last_name           VARCHAR(100),

    -- professional
    company_name        VARCHAR(200),
    vat_number          VARCHAR(50),
    registration_number VARCHAR(50),
    annual_revenue      DECIMAL(19, 2)
);

CREATE TABLE shopping_carts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    VARCHAR(50)    NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_cart_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE cart_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id      BIGINT      NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    quantity     INT         NOT NULL,

    CONSTRAINT fk_item_cart
        FOREIGN KEY (cart_id) REFERENCES shopping_carts (id)
);
