CREATE TABLE price_rules
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_type           VARCHAR(20)    NOT NULL,
    min_revenue_exclusive DECIMAL(19, 2),
    max_revenue_inclusive DECIMAL(19, 2),
    product_type          VARCHAR(30)    NOT NULL,
    price                 DECIMAL(19, 2) NOT NULL
);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('INDIVIDUAL', NULL, NULL, 'HIGH_END_PHONE', 1500.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('INDIVIDUAL', NULL, NULL, 'MID_RANGE_PHONE', 800.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('INDIVIDUAL', NULL, NULL, 'LAPTOP', 1200.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', NULL, 10000000.00, 'HIGH_END_PHONE', 1150.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', NULL, 10000000.00, 'MID_RANGE_PHONE', 600.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', NULL, 10000000.00, 'LAPTOP', 1000.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', 10000000.00, NULL, 'HIGH_END_PHONE', 1000.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', 10000000.00, NULL, 'MID_RANGE_PHONE', 550.00);

INSERT INTO price_rules (client_type, min_revenue_exclusive, max_revenue_inclusive, product_type, price)
VALUES ('PROFESSIONAL', 10000000.00, NULL, 'LAPTOP', 900.00);
